### ISSUE TITLE
Incorrect Timezone offset is used

### ISSUE THREAD

**Issue by JonnoFTW** [mmerickel/request-id#3]
Using the default config and having a timezone with a half hour offset will produce a timestamp of xx50 instead of xx30:

```
127.0.0.1 localhost:6868 - [27/Nov/2017:11:52:03 +1050] "GET http://localhost:6868/ HTTP/1.0" 200 6656 0.079 "-" "Mozilla/5.0 
```

Problem is here:

https://github.com/mmerickel/request-id/blob/master/request_id/__init__.py#L104-L111

My solution would be to introduce tzlocal as a depency and use the following code:

```python
from datetime import datetime
import tzlocal
timestamp = datetime.now().astimezone(tzlocal.get_localzone()).strftime('%d/%b/%Y:%H:%M:%S %z')
```

**Comment by mmerickel** [comment]
Can you give me an example timestamp and timezone?

**Comment by JonnoFTW** [comment]
Example timezone is Australia/Adelaide with +1030, timestamp displayed is:

```
27/Nov/2017:11:52:03 +1050
```

Expected:

```
27/Nov/2017:11:52:03 +1030
```
